import "~/styles/globals.css";
import { Roboto } from "next/font/google";
import { Sidebar } from "~/components/Sidebar";

const roboto = Roboto({
    subsets: ["latin"],
});

export const metadata = {
    title: "Simplebooks",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${roboto.className} flex flex-col bg-[#fffcf2]`}>
            <Sidebar />
            <main className="w-full flex-1">{children}</main>
        </body>
        </html>
    );
}
