import "~/styles/globals.css";
import { Roboto } from "next/font/google";
import { Sidebar } from "~/components/Sidebar";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: "T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex flex-col bg-[#fffcf2]`}>
        <div className="flex">
          <div className="w-full flex justify-center">
            <Sidebar/>
          </div>
        </div>
        <main className="w-full flex-1">{children}</main>
      </body>
    </html>
  );
}